name: Deploy to IONOS

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                  node-version: 24
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm run test

            - name: Build site
              run: npm run build

            - name: Install lftp
              run: sudo apt-get update && sudo apt-get install -y lftp

            - name: Deploy via SFTP
              run: |
                  lftp -u "${{ secrets.HOMEPAGE_USER }}","${{ secrets.HOMEPAGE_PASSWORD }}" sftp://${{ secrets.HOMEPAGE_HOST }} <<EOF
                  set sftp:auto-confirm yes
                  set net:max-retries 2
                  set net:timeout 20
                  mirror -R --verbose ./docs/ ${{ secrets.HOMEPAGE_TARGET_DIR }}
                  bye
                  EOF
